config/routes.rb
Buynance::Application.routes.draw do

  devise_for :rep_dialers, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope(:path_names => { :new => "merchant-cash-advance" }) do
    resources :profitabilities, :path => "calculator", :only => [:new, :create]
  end

  resources :static_pages, :except => [:new, :create, :show, :update, :destroy, :index, :edit] do
    collection do
      get 'about'
      get 'offer'
      get 'tos'
      get 'confirm_email'
      get 'error'
      get 'compare'
    end
  end
  
  resources :funder_dashboards, only: [:main, :make_offer, :pending_bids, :accepted_bids, :lost_bids, :won_bids], path: "funder_dashboard" do
    collection do
      get 'main'
      post 'make_offer'
      get 'pending_bids'
      get 'accepted_bids'
      get 'lost_bids'
      get 'won_bids'
    end
  end

  resources :businesses, :only => [:new, :create, :show], :path => "clients" do
    resources :offers, :only => [:index] do
      patch :accept
    end
    resources :bank_accounts
    member do
      patch :activate
    end
    collection do
      get 'show_offers'
      get 'confirm_account'
      post 'confirm_mobile'
      get 'disqualified'
      get 'qualified_market'
      get 'accept_offer'
    end
  end

  
  mount API::Base => '/api'
  mount Soulmate::Server, :at => "/sm"
  scope(:path_names => { :past_merchants => "funders", :financial_information => "financial" }) do
    resources :business_steps, :path => "register"
  end

  resources :funders
  resources :funding_steps, :path => "funding"
  resources :funder_sessions, :path => "funder_session", :only => [:new, :create, :destoy]
  resources :business_user_sessions, :path => "session", :only => [:new, :create, :destoy]
  
  resources :business_dashboards, :only => [:display_offers, :offer_accepted, :offer_funded, :reenter_market, :accept_offer] do
    collection do
      get "display_offers"
      get "offer_accepted", as: :offer_accepted
      get "offer_funded", as: :offer_funded
      get "reenter_market", as: :reenter_market
      post "accept_offer", as: :accept_offer
    end
  end

  resources :dialer_dashboards, only: [:home, :setup, :setup_action, :account], path: "friends" do
    collection do
      get 'home', as: :dialer_home
      get 'account', as: :dialer_account
      patch 'setup_action', as: :setup_action
      get 'setup', as: :setup
      get 'questionnaire', as: :questionnaire
      patch 'questionnaire_action', as: :questionnaire_action
    end
  end

  resources :family_dashboards, only: [:home, :setup, :setup_action, :account, :sign_in], path: "family" do
    collection do
      get 'home', as: :dialer_home
      get 'account', as: :dialer_account
      patch 'setup_action', as: :setup_action
      get 'setup', as: :setup
      get 'questionnaire', as: :questionnaire
      patch 'questionnaire_action', as: :questionnaire_action
      get 'sign_in', as: :sign_in
    end
  end

  get 'friends' => 'dialer_dashboards#home'
  get 'family' => 'family_dashboards#home'

  get 'offers' => 'business_dashboards#display_offers', as: :display_offers

  

  get 'login' => "business_user_sessions#new",      :as => :login
  get 'logout' => "business_user_sessions#destroy", :as => :logout
  get 'funder_login' => "funder_sessions#new",      :as => :funder_login
  get 'funder_logout' => "funder_sessions#destroy", :as => :funder_logout

  get '/signup' => 'businesses#new', :as => :signup
  get '/account' => 'businesses#show', :as => :account

  get 'tos'                   => 'static_pages#tos'
  get 'privacy'               => 'static_pages#privacy'
  get 'business-funding-calculator' => 'profitabilities#new'
  get 'blog'                  => 'static_pages#blog'
  get 'about'                 => 'static_pages#about'
  get 'products'                 => 'static_pages#compare'

  match 'activate/:activation_code' => "businesses#activate", via: :get
  post 'confirm_mobile' => 'businesses#confirm_mobile'

  get 'details' => 'businesses#details'
  get 'clients/twiml/:id' => 'businesses#twiml'
  
  get 'DLPHP/verification.php' => "bank_accounts#new"
  get '/bank_accounts/success' => "bank_accounts#success"
  get '/bank_accounts/failure' => "bank_accounts#failure", as: :bank_failure

  get '/offers/:offer_id/accept' => 'offers#accept'
  put '/offers/:offer_id/update' => 'offers#update'

  post 'user/recover_account'    => 'business_users#recover_account'
  post 'user/reset_password'     => "business_users#reset_password"
  get 'recover'                  => 'business_users#recover', :as => :recovery_path
  get 'activation'               => 'business_users#recovery_instructions', :as => :recovery_instructions_path
  get 'recover/:recovery_code' => "business_users#password", as: :recovery_password

  get 'dummy' => "static_pages#dummy"
  
  post 'call/:id' => 'routing_numbers#call'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  

  match '/', to: 'static_pages#dev', constraints: { subdomain: 'dev' }, via: [:get, :post, :put, :patch, :delete]
  match '/invite', to: 'contest#invite', constraints: { subdomain: 'dev' }, via: [:get, :post, :put, :patch, :delete]

  root 'static_pages#index'

  

end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
	belongs_to :business_type_division, inverse_of: :business_types

	has_many :businesses
end

app/controllers/businesses_controller.rb
require 'decision_logic.rb'
require 'twilio_lib'

class BusinessesController < ApplicationController
  before_filter :require_business_user, :only => [:show, :accept_offer, :activate_account, :confirm_account, :confirm_mobile, :qualified_funder, :qualified_market, :disqualified]
  before_filter :require_no_business_user, :only => [:new, :create]
  before_filter :grab_business_and_business_user, :only => [:show]
  before_filter :send_production_js, only: [:new, :qualified_funder, :qualified_market, :disqualified]
  #before_filter :standardize_params, :only => [:create]


  def new 
      @business_user = BusinessUser.new 
      @business = Business.new   
  end

  def create
    @business = Business.new(business_params)
    @business_user = BusinessUser.new(business_user_params)
    @business.is_refinance = false
    
    if @business_user.valid? && @business.valid?
      @business_user.save
      @business.save
      @business_user.update_attribute(:business_id, @business.id)
      @business.update_attribute(:main_business_user_id, @business_user.id)
      @business.update_attribute(:email, @business_user.email)
      flash[:signup] = true
      redirect_to funding_steps_path
    else
      render :action => :new
    end
  end

  def show 
    if @business.disqualified?
      render :action => :disqualified
    elsif @business.bank_error?
      redirect_to bank_failure_path
    elsif @business.awaiting_personal_information? or @business.awaiting_bank_information?
      redirect_to funding_steps_path
    elsif @business.awaiting_email_confirmation?
      redirect_to controller: 'static_pages', action: 'confirm_email'
    elsif @business.awaiting_mobile_confirmation?
      redirect_to action: 'confirm_account'
    elsif @business.qualified_for_market? || @business.accepted_buynance_fast_advance? || @business.accepted_buynance_fast_advance_plus? || @business.accepted_affiliate_advance?
      redirect_to action: 'qualified_market'
    elsif @business.disqualified_for_refi? || @business.disqualified_for_funder?
      redirect_to action: 'disqualified'
    elsif @business.awaiting_offer_acceptance?
      redirect_to display_offers_url
    elsif @business.awaiting_offer_completetion?
      redirect_to controller: 'business_dashboards', action: 'offer_accepted'
    elsif @business.awaiting_reenter_market?
      redirect_to reenter_market_url
    else
      redirect_to action: :error
    end
  end

  def details
    @business = Business.new
  end

  def activate_account 
    @business = current_business
  end

  def not_qualified
    @business = current_business
  end

  def activate
    @business = Business.where("activation_code = ? AND state = ?", params[:activation_code], "awaiting_email_confirmation").last
    
    unless @business.nil?
      @business.email_confirmation_provided
      @business.send_mobile_confirmation!
      flash[:is_email_confirmed] = true
      flash[:success_activation_message] = "Your account has been activated. Please login to continue with your application."
    else
      flash[:faliure_activation_message] = "Your account is already activated or the activation link is invalid."
    end
    redirect_to :action => :show
  end

  def show_offers
    @business = current_business
    @offers = @business.leads.last.offers
  end

  def error
    
  end

  def confirm_account
    pluggable_js(email: current_business.business_user.email, is_production: is_production, is_email_confirmed: (flash[:is_email_confirmed] == true))
    @business = current_business
    @business.passed_email_confirmation
  end

  def confirm_mobile
    business = current_business
    if business.mobile_opt_code == params[:mobile][:mobile_opt_code]
      if business.qualify
        business.passed_mobile_confirmation 
        business.mobile_confirmation_provided
        business.qualify_for_market
      else
        business.mobile_confirmation_provided
        business.passed_mobile_confirmation
        business.disqualify
      end
      
      redirect_to action: :show
    else
      flash[:alert] = "Mobile code is incorrect. Please try again."
      render :confirm_account
    end
  end

  def twiml
    business = Business.find(params[:id])
    twiml = ""
    twiml = TwilioLib.generate_voice_xml(business.mobile_number) unless business.nil?
    
    render xml: twiml
  end

  def qualified_funder
  end

  def qualified_refi
  end

  def qualified_market
    @business = current_business 
    @business.passed_mobile_confirmation
    @has_offers = @business.offers.size > 2
  end

  def disqualified
  end

  def accept_offer
    @business = current_business 
    offer_type = params[:offer]
    if offer_type == "1"
      @business.accept_buynance_fast_advance
    elsif offer_type == "2"
      @business.accept_buynance_fast_advance_plus
    elsif offer_type == "3"
      @business.accept_affiliate_advance
    end
    redirect_to :action => :show
  end


  private


    def business_user_params
      return params.require(:business_user).permit(:email, 
        :password, :password_confirmation, :email_confirmation) 
    end

    def business_params
      return params.require(:business).permit(:terms_of_service, :recovery_code, :name, :is_refinance, :referral_code, :discovery_type_id) 
    end

    def accept_offer_params
      return params.require(:accept_offer).permit(:offer) 
    end

end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.haml
%div{class: "form_group #{return_error_class(@business, :loan_reason_id)} row"}
  %label{class: "control-label", :for => :loan_reason_id} 
    What do you need the money for?
  %br
  = f.select :loan_reason_id, options_for_select({"Invest In Marketing" => 0, "Pay Old Bills" => 1, "Expansion" => 2, "Payroll" => 3, "Invest In Inventory" => 4, "Capital Improvements" => 5, "Pay Rent / Mortgage" => 6}),{  }, {:class => "form-control selectpicker", style:"text-align: center;"}

%div{class: "form_group #{return_error_class(@business, :earned_one_month_ago)}"}
  %label{class: "control-label", :for => :earned_one_month_ago} 
    How much did your business earn in 
    = x_months_ago_string(1) + "?"
  = f.text_field :earned_one_month_ago, class: "text-center form-control currency_convert", required: true

%div{class: "form_group #{return_error_class(@business, :earned_two_months_ago)}"}
  %label{class: "control-label", :for => :earned_two_months_ago} 
    How much did your business earn in  
    = x_months_ago_string(2) + "?"
  = f.text_field :earned_two_months_ago, class: "text-center form-control currency_convert", required: true

%div{class: "form_group #{return_error_class(@business, :earned_three_months_ago)}"}
  %label{class: "control-label", :for => :earned_three_months_ago} 
    How much did your business earn in  
    = x_months_ago_string(3) + "?"
  = f.text_field :earned_three_months_ago, class: "text-center form-control currency_convert", required: true

= fields_for :business_user, @business do |bf| 
  %div{class: "form_group #{return_error_class(@business, :email)}"}
    %label{class: "control-label", :for => :email} 
      Email
    = bf.text_field :email, class: "text-center form-control ", required: true

  %h3 Create Your Buynance Password

  %div{class: "form_group #{return_error_class(@business, :password)}"}
    %label{class: "control-label", :for => :password} 
      Enter new Buynance password
    = bf.password_field :password, class: "text-center form-control ", required: true

  %div{class: "form_group #{return_error_class(@business, :password_confirmation)}"}
    %label{class: "control-label", :for => :password_confirmation} 
      Re-enter Buynance password
    = bf.password_field :password_confirmation, class: "text-center form-control "

%div{class: "form_group #{return_error_class(@business, :terms_of_service)}"}  
  = f.check_box :terms_of_service
  %label{class: "control-label", :for => :terms_of_service, style: "margin-left: 10px;"}
    I agree to the 
    %a{href: "http://buynance.com/tos"}  
      Terms of Service 

= f.submit "Next Step", class: "btn btn-primary btn-lg btn-lg btn-block green-btn"

app/views/businesses/_offer_list.html.haml
.main_body.form-style
  %h3.form-header
    = "You Have #{@business.offers.size} Offers!"
  .row.offer-body
    - for i in 0...(@business.offers.size)/2
      - offer = @business.offers[i]
      = render :partial => "offer_section", :locals => {:offer => offer, :i => i} 

    - for i in (@business.offers.size/2)...@business.offers.size
      .hidden-offers
        - offer = @business.offers[i]
        = render :partial => "offer_section", :locals => {:offer => offer, :i => i}
  %ul.pager
    %li
      %a{class: "btn btn-default", onclick: "display_offers()"} View Others

#disclaimerModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "disclaimerModal", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %p.MsoNormal{style: "text-align:center;"}
          %b{style: "mso-bidi-font-weight:normal"}
            %span{style: "font-size:14.0pt;font-family:\r\nHelvetica;mso-fareast-font-family:\"Times New Roman\";mso-bidi-font-family:Arial;\r\ncolor:#365F91;mso-themecolor:accent1;mso-themeshade:191;background:white; text-align: center;"}
              NOTICE: Please be sure that the information you provided is correct and accurate.
      .modal-body
        %textarea{readonly: "readonly", rows: 7, cols: 60, style: "resize: none;"}
          = " I understand that the offers I am about to receive are based on the information I have provided.I understand that false or misleading information may jeopardize my ability to access the Buynance service. I understand that merchant cash advance brokers and funders frequently place unsolicited telephone calls to business owners like me, so as to offer me help in either finding a merchant cash advance, or taking one from their firm. I understand that merchant cash advance brokers and funders frequently place unsolicited telephone calls to business owners like me, so as to offer me help in either finding a merchant cash advance, or taking one from their firm. I understand that this is the norm and that in accordance with its Terms of Service Buynance will not broker or sell my information to any third party vendors for any reason whatsoever. I understand that Buynance only supplies my phone number to the funder whose offer I have chosen during the funding pre-qualification process. I understand that Buynance helps funders understand my time is valuable but also understand that Buynance cannot be held responsible for any persistent follow up made by the funder whose offer I chose. I understand that if the funder whoseÕ offer I chose becomes overbearing then I may file a formal complaint with Buynance at complaints@buynance.com. I expressly authorize Funder Pair Inc to call me or send me recorded messages or texts about their products and services using automated technology to my telephone/cellular number I will enter at the completion of the Buynance online pre-qualification process, regardless of any prior Do-Not-Call election to the contrary. I understand that I am not required to give my consent as a condition of any purchase."
      .modal-footer
        %button.btn.btn-default{type: "button", "data-dismiss" => "modal"} 
          Go Back
        %button.btn.btn-green{type: "button", onclick: "accept_offer_disclaimer(this)"}
          Accept Offer
         

  :javascript

    $('.button .btn.offer-btn').click(function(){
      var id = $(this).data('id');
      $('#disclaimerModal').find('button.btn').data("id", id);
    });

    function display_offers(){
      $(".hidden-offers" ).css("display", "block");
      $(".pager").css("display", "none");
    }

    function accept_offer_disclaimer(node){
      var update_url;
      var id = $(node).closest("#disclaimerModal").data('id');
      window.location = "/offers/"+id+"/accept";
    }

    function show_modal(node){
      $('#disclaimerModal').modal('show')
      id = $(node).closest(".offer").data("id")
      $('#disclaimerModal').data("id", id)
    }

app/views/businesses/_password_form.html.haml
f.hidden_field :recovery_code, value: @business.recovery_code
%div{class: "form_group #{return_error_class(@business, :password)}"}
  %label{class: "control-label", :for => :password} 
    Enter new Buynance password
  = f.password_field :password, class: "text-center form-control ", required: true

%div{class: "form_group #{return_error_class(@business, :password_confirmation)}"}
  %label{class: "control-label", :for => :password_confirmation} 
    Re-enter Buynance password
  = f.password_field :password_confirmation, class: "text-center form-control "

= f.submit "Reset Password", class: "btn btn-primary btn-lg btn-lg btn-block green-btn"

app/views/businesses/bank_information.html.haml
.web_body
  .module
    %ul
      %li.tab.activeTab
        %img.icon{alt: "", src: "http://i.imgur.com/Fk1Urva.png"}/
      %li.tab
        %img.icon{alt: "", src: "http://i.imgur.com/ZsRgIDD.png"}/
      %li.tab
        %img.icon{alt: "", src: "http://i.imgur.com/34Q50wo.png"}/
      %li.tab
        %img.icon{alt: "", src: "http://i.imgur.com/LCCJ06E.png"}/
    .form
      = simple_form_for @business do |f|
        - if @business.errors.any? || @business_user.errors.any?
          %div{class: "alert alert-danger validation-errors"}
            %ul{style: "list-style: none;"}
              - @business.errors.full_messages.each do |msg|
                %li= msg
              - @business_user.errors.full_messages.each do |msg|
                - if /[[:upper:]]/.match(msg[0])
                  %li= msg
        = f.input :email, placeholder: 'Email', input_html: {class: 'textbox'}, label: false
        = f.input :password, placeholder: 'Password', input_html: {class: 'textbox'}, label: false
        = f.input :password_comfirmation, placeholder: 'Password Comfirmation', input_html: {class: 'textbox'}, label: false
        /= f.input :terms_of_service, as: :boolean, label: false
        = f.submit'Next', class: 'form-button'

app/views/businesses/confirm_account.html.haml
.web_body
  .paper-section
    .paper-section-header
      Mobile Confirmation
    .paper-section-main.clearfix   
      .paper-section-main-sheet.first-paper-section.clearfix
        .paper-section-main-sheet.last-paper-section
          .paper-section-bank-login.row
            .paper-section-bank-login-left.col-xs-7
              .paper-section-bank-login-left-header
                %span Please Confirm your Mobile Number
              .paper-section-bank-login-left-information
                %span To protect your privacy and combat against fraud, we have sent an account confirmation code to your mobile number phone.  Please enter it below.                
              .paper-section-bank-login-form
                = simple_form_for :mobile, url: '/confirm_mobile' do |f|
                  - unless flash.alert.nil?
                    %div{class: "alert alert-danger validation-errors"}
                      %ul{style: "list-style: none;"}
                        %li 
                          = flash.alert
                  .paper-section-bank-login-form-label
                    %span We just sent you a text message, enter the code below.
                  .paper-section-bank-login-form-input
                    = f.input :mobile_opt_code, placeholder: 'Mobile Code', input_html: {class: 'textbox'}, label: false, as: :string
                  .paper-section-bank-login-form-action
                    = f.submit "Continue", class: "form-button flat-button button-submit"
            .paper-section-bank-login-right.col-xs-5
              = render "shared/funding_sidebar"

app/views/businesses/disqualified.haml
.web_body
  .paper-section
    .paper-section-header
      %span Qualification
    .paper-section-main.clearfix   
      .paper-section-main-sheet.first-paper-section.clearfix
        .paper-section-main-sheet.last-paper-section
          .paper-section-bank-login.row
            .email-confirmation
              .email-confirmation-header
                %span Sorry you do not qualify.
              .email-confirmation-body
                .email-confirmation-body-info
                  %span Unfortunately, we will not be able to help you secure business funding at this time. We wish you the best in your search to secure business funding.

app/views/businesses/error.html.haml
.web_body
  .module
    %ul
      %li.tab.activeTab
        %img.icon{alt: "", src: "http://i.imgur.com/Fk1Urva.png"}/
      %li.tab
        %img.icon{alt: "", src: "http://i.imgur.com/ZsRgIDD.png"}/
      %li.tab
        %img.icon{alt: "", src: "http://i.imgur.com/34Q50wo.png"}/
      %li.tab
        %img.icon{alt: "", src: "http://i.imgur.com/LCCJ06E.png"}/
    .form
      Sorry there was an error please contact us

app/views/businesses/qualified_market.html.haml
:javascript
  $(window).load(function(){
      $('#myModal').modal('show');
  });

.web_body
  .paper-section.acceptance-main
    .paper-section-header.acceptance-header
      %span Congrats!
    .acceptance
      .acceptance-top.clearfix
        .acceptance-top-image
          = image_tag("yuliya_account.png")
          .name{:style => "text-align: center;margin-top: 20px;font-family: latobold;font-size: 20px;color: #25aae1;"}
            %span Yuliya Glazman
        .acceptance-top-info
          .acceptance-top-info-greeting
            %span 
              = "Hi #{@business.owner_first_name},"
          .acceptance-top-info-message
            %span Congrats!  It looks like you’ve been pre-approved to receive small business funding through Buynance.  Please evaluate your next steps and all options below.
      .acceptance-body.clearfix
        .acceptance-item-gray
          .acceptance-item-gray-title
            %span Buynance Fast Advance™
          .acceptance-item-gray-subtitle
            %span Get 
            - if @business.offers.size > 0
              %span.highlight-green 
                = number_to_currency(@business.offers[0].cash_advance_amount.round(0), precision: 0) 
            - else
              %span.highlight-green $2,000
            %span in as little as one hour.
          .acceptance-item-gray-list.acceptance-list-one
            %span No credit check.
          .acceptance-item-gray-list.acceptance-list-two
            %span Simple application.
          .acceptance-item-gray-terms
            .acceptance-item-gray-terms-title
              %span Overview
            .acceptance-item-gray-terms-item
              %span You sell us 
              - if @has_offers
                %span.highlight-green{style: "font-family: latobold"} 
                  = number_to_currency(@business.offers[0].total_payback_amount.round(0), precision: 0)
                %span worth of you future sales, we will give you 
                %span 
                  = number_to_currency(@business.offers[0].cash_advance_amount.round(0).to_i, precision: 0) 
                %span cash for them in as little as an hour. 
              - else
                %span.highlight-green{style: "font-family: latobold"} $2,800 
                %span worth of you future sales, we will give you $2,000 cash for them in as little as an hour. 
            .acceptance-item-gray-terms-item
              %span We collect the 
              - if @has_offers
                %span.highlight 
                  = number_to_currency(@business.offers[0].total_payback_amount.round(0).to_i)
              - else
                %span.highlight $2,800
              %span over 45 days.
            - if @business.accepted_market?
              .acceptance-item-gray-terms-item
                %span No early payment penalty.
            - else
              .acceptance-item-gray-terms-item{style: "border-bottom-width: 0px;"}
                %span No early payment penalty.
          .acceptance-item-gray-terms-submit
            - if @business.accepted_market?
              = link_to accept_offer_businesses_path(offer: "1"), class: "flat-button button-plan" do
                %span CHOOSE PLAN
              

        .acceptance-item-green
          .acceptance-item-green-title
            %span Buynance Fast Advance Plus™
          .acceptance-item-green-subtitle
            - if @has_offers
              %span Get 
              %span 
                = number_to_currency((@business.offers[1].cash_advance_amount).round(0), precision: 0)
              %span .
              %span 
                = number_to_currency((@business.offers[1].cash_advance_amount * 0.0625).round(0), precision: 0)
              %span today and 
              %span 
                = number_to_currency((@business.offers[1].cash_advance_amount * 0.9375).round(0), precision: 0)
              %span in 7 Days.
            - else
              %span Get $25,000. $3,500 today and $21,500 in 7 Days.
          .acceptance-item-green-subtitle-two
            %span Get 
            - if @has_offers
              %span.highlight-green{style: "font-family: latobold"} 
                = number_to_currency((@business.offers[1].cash_advance_amount * 0.0625).round(0), precision: 0)
            - else 
              %span.highlight-green{style: "font-family: latobold"} $3,500 
            %span in your account in one hour and 
            - if @has_offers
              %span.highlight-green{style: "font-family: latobold"} 
                = number_to_currency((@business.offers[1].cash_advance_amount * 0.9375).round(0), precision: 0)
            - else
              %span.highlight-green{style: "font-family: latobold"} $21,500
            %span in 7 days from one of our preferred partners.
          .acceptance-item-green-terms-item.acceptance-item-green-terms-item-odd
            %span Guaranteed approval.
          .acceptance-item-green-terms-item.acceptance-item-green-terms-item-even
            %span Simple application.
          .acceptance-item-green-terms-item.acceptance-item-green-terms-item-odd
            %span No broker fees.
          .acceptance-item-gray-terms
            .acceptance-item-gray-terms-title
              %span Overview
            .acceptance-item-gray-terms-item
              %span You sell us 
              - if @has_offers
                %span.highlight-green{style: "font-family: latobold"} 
                  = number_to_currency((@business.offers[1].total_payback_amount.round(0)), precision: 0) 
                %span worth of you future sales, we will give you 
                %span 
                  = number_to_currency((@business.offers[1].cash_advance_amount * 0.0625).round(0), precision: 0) 
                %span cash for them in as little as an hour. 
              - else
                %span.highlight-green{style: "font-family: latobold"} $2,800 
                %span worth of you future sales, we will give you $2,000 cash for them in as little as an hour. 
            .acceptance-item-gray-terms-item
              %span We collect the 
              - if @has_offers
                %span
                  = number_to_currency(@business.offers[1].total_payback_amount.round(0), precision: 0)
              - else
                %span $2,800 
              %span over 30 daily installments. OR,
            - if @business.accepted_market?
              .acceptance-item-gray-terms-item
                %span You complete the sale when you get more cash in a week. 
            - else
              .acceptance-item-gray-terms-item{style: "border-bottom-width: 0px;"}
                %span You complete the sale when you get more cash in a week.
          .acceptance-item-green-terms-submit
            - if @business.accepted_market?
              = link_to accept_offer_businesses_path(offer: "2"), class: "flat-button button-plan" do
                %span CHOOSE PLAN

        .acceptance-item-gray
          .acceptance-item-gray-title
            %span Affiliate Advance
          .acceptance-item-gray-subtitle
            %span Get 
            - if @has_offers
              %span.highlight-green
                = number_to_currency(@business.offers[2].cash_advance_amount.round(0), precision: 0)
            - else
              %span.highlight-green $25,000
            %span in your account in 7 days.
          .acceptance-item-gray-list.acceptance-list-one
            %span Credit check required.
          .acceptance-item-gray-list.acceptance-list-two
            %span Minimal paperwork.
          .acceptance-item-gray-terms
            .acceptance-item-gray-terms-title
              %span Overview
            .acceptance-item-gray-terms-item
              %span Guaranteed approval.
            .acceptance-item-gray-terms-item
              %span Simple application process.
            - if @business.accepted_market?
              .acceptance-item-gray-terms-item
                %span Closing costs may apply.
            - else
              .acceptance-item-gray-terms-item{style: "border-bottom-width: 0px"}
                %span Closing costs may apply.
          .acceptance-item-gray-terms-submit
            - if @business.accepted_market?
              = link_to accept_offer_businesses_path(offer: "3"), class: "flat-button button-plan" do
                %span CHOOSE PLAN

- unless @business.accepted_market?
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h4.modal-title{style: "font-family: latobold; font-size: 20px; color: #8dc63f;"} Plan Selected
        .modal-body{style: "font-family: lato; font-size: 15px;"}
          %p Great! Your submission is being processed.  Please check your e-mail for the next steps.
      / /.modal-content
    / /.modal-dialog
  / /.modal
