config/routes.rb
Buynance::Application.routes.draw do

  devise_for :rep_dialers, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope(:path_names => { :new => "merchant-cash-advance" }) do
    resources :profitabilities, :path => "calculator", :only => [:new, :create]
  end

  resources :static_pages, :except => [:new, :create, :show, :update, :destroy, :index, :edit] do
    collection do
      get 'about'
      get 'offer'
      get 'tos'
      get 'confirm_email'
      get 'error'
      get 'compare'
    end
  end
  
  resources :funder_dashboards, only: [:main, :make_offer, :pending_bids, :accepted_bids, :lost_bids, :won_bids], path: "funder_dashboard" do
    collection do
      get 'main'
      post 'make_offer'
      get 'pending_bids'
      get 'accepted_bids'
      get 'lost_bids'
      get 'won_bids'
    end
  end

  resources :businesses, :only => [:new, :create, :show], :path => "clients" do
    resources :offers, :only => [:index] do
      patch :accept
    end
    resources :bank_accounts
    member do
      patch :activate
    end
    collection do
      get 'show_offers'
      get 'confirm_account'
      post 'confirm_mobile'
      get 'disqualified'
      get 'qualified_market'
      get 'accept_offer'
    end
  end

  
  mount API::Base => '/api'
  mount Soulmate::Server, :at => "/sm"
  scope(:path_names => { :past_merchants => "funders", :financial_information => "financial" }) do
    resources :business_steps, :path => "register"
  end

  resources :funders
  resources :funding_steps, :path => "funding"
  resources :funder_sessions, :path => "funder_session", :only => [:new, :create, :destoy]
  resources :business_user_sessions, :path => "session", :only => [:new, :create, :destoy]
  
  resources :business_dashboards, :only => [:display_offers, :offer_accepted, :offer_funded, :reenter_market, :accept_offer] do
    collection do
      get "display_offers"
      get "offer_accepted", as: :offer_accepted
      get "offer_funded", as: :offer_funded
      get "reenter_market", as: :reenter_market
      post "accept_offer", as: :accept_offer
    end
  end

  resources :dialer_dashboards, only: [:home, :setup, :setup_action, :account], path: "friends" do
    collection do
      get 'home', as: :dialer_home
      get 'account', as: :dialer_account
      patch 'setup_action', as: :setup_action
      get 'setup', as: :setup
      get 'questionnaire', as: :questionnaire
      patch 'questionnaire_action', as: :questionnaire_action
    end
  end

  resources :family_dashboards, only: [:home, :setup, :setup_action, :account, :sign_in], path: "family" do
    collection do
      get 'home', as: :dialer_home
      get 'account', as: :dialer_account
      patch 'setup_action', as: :setup_action
      get 'setup', as: :setup
      get 'questionnaire', as: :questionnaire
      patch 'questionnaire_action', as: :questionnaire_action
      get 'sign_in', as: :sign_in
    end
  end

  get 'friends' => 'dialer_dashboards#home'
  get 'family' => 'family_dashboards#home'

  get 'offers' => 'business_dashboards#display_offers', as: :display_offers

  

  get 'login' => "business_user_sessions#new",      :as => :login
  get 'logout' => "business_user_sessions#destroy", :as => :logout
  get 'funder_login' => "funder_sessions#new",      :as => :funder_login
  get 'funder_logout' => "funder_sessions#destroy", :as => :funder_logout

  get '/signup' => 'businesses#new', :as => :signup
  get '/account' => 'businesses#show', :as => :account

  get 'tos'                   => 'static_pages#tos'
  get 'privacy'               => 'static_pages#privacy'
  get 'business-funding-calculator' => 'profitabilities#new'
  get 'blog'                  => 'static_pages#blog'
  get 'about'                 => 'static_pages#about'
  get 'products'                 => 'static_pages#compare'

  match 'activate/:activation_code' => "businesses#activate", via: :get
  post 'confirm_mobile' => 'businesses#confirm_mobile'

  get 'details' => 'businesses#details'
  get 'clients/twiml/:id' => 'businesses#twiml'
  
  get 'DLPHP/verification.php' => "bank_accounts#new"
  get '/bank_accounts/success' => "bank_accounts#success"
  get '/bank_accounts/failure' => "bank_accounts#failure", as: :bank_failure

  get '/offers/:offer_id/accept' => 'offers#accept'
  put '/offers/:offer_id/update' => 'offers#update'

  post 'user/recover_account'    => 'business_users#recover_account'
  post 'user/reset_password'     => "business_users#reset_password"
  get 'recover'                  => 'business_users#recover', :as => :recovery_path
  get 'activation'               => 'business_users#recovery_instructions', :as => :recovery_instructions_path
  get 'recover/:recovery_code' => "business_users#password", as: :recovery_password

  get 'dummy' => "static_pages#dummy"
  
  post 'call/:id' => 'routing_numbers#call'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  

  match '/', to: 'static_pages#dev', constraints: { subdomain: 'dev' }, via: [:get, :post, :put, :patch, :delete]
  match '/invite', to: 'contest#invite', constraints: { subdomain: 'dev' }, via: [:get, :post, :put, :patch, :delete]

  root 'static_pages#index'

  

end

app/controllers/family_dashboards_controller.rb
 class FamilyDashboardsController < ApplicationController

	layout "family_layout"

	before_filter :require_rep_dialer_family, except: [:home, :iso_home, :sign_in]

	force_ssl if: :not_linkedin?

	def home
		 pluggable_js(is_production: is_production)

	end

	def iso_home

	end

	def account

		@representative = current_rep_dialer_family
		pluggable_js(is_production: is_production, email: @representative.email, is_pending: @representative.awaiting_acceptance?, is_accepted: @representative.accepted?, is_rejected: @representative.rejected?)
		if @representative.awaiting_questionnaire?
			redirect_to action: :questionnaire
		end
	end

	def setup
		@representative = current_rep_dialer_family
	end

	def setup_action
		@representative = current_rep_dialer_family
		if @representative.update_attributes(representative_params)
			@representative.add_paypal
			redirect_to action: :account
		else
			render action: :setup
		end
	end

	def questionnaire
		@rep_dialer = current_rep_dialer_family
		pluggable_js(is_production: is_production, email: @rep_dialer.email)
		@questionnaire = Questionnaire.find_by(name: "family_questionnaire")
	end

	def questionnaire_action
		@rep_dialer = current_rep_dialer_family
		@questionnaire = Questionnaire.find_by(name: "rep_questionnaire")
		@rep_dialer.assign_attributes(representative_params)
		@rep_dialer.current_step = "questionnaire"
		#@questionnaire.assign_attributes(questionnaire_params)
		if ((@questionnaire.valid? and @rep_dialer.valid?) and @rep_dialer.role == "Friend") or (@rep_dialer.valid? and @rep_dialer.role == "Family")
			@questionnaire.save
			@rep_dialer.save
			(0...@questionnaire.questions.size).each do |i|
				question = @questionnaire.questions[i]
				Answer.create(answer_text: @questionnaire.send("answer#{i+1}".to_sym),
					question_id:  @questionnaire.questions[i].id, 
					rep_dialer_id: @rep_dialer.id)
			end
			QuestionnaireCompleted.create(questionnaire_id: @questionnaire.id, rep_dialer_id: @rep_dialer.id)
			@rep_dialer.complete_questionnaire
			redirect_to action: :account
		else
			render action: :questionnaire
		end
	end

	def sign_in
		session[:family_signup] = "true"
		session[:dialer_resource] = "Family"
		redirect_to rep_dialer_omniauth_authorize_path(provider: "linkedin", type: "Family"), method: :post
	end

	private

	def representative_params
      return params.require(:rep_dialer).permit(:mobile_number, :agree_confirmation) 
    end

    def questionnaire_params
    	return params.require(:questionnaire).permit(:answer1, :answer2, :answer3, :answer4, :answer5)
    end

    def not_linkedin?
    	((params[:linkedin] != "true") and !Rails.env.development?)
    end

end

app/views/family_dashboards/account.html.haml
.web_body
  .paper-section
    .paper-section-header
      %span Account
    .paper-section-main.clearfix   
      .paper-section-main-sheet.first-paper-section.clearfix
        .paper-section-main-sheet.last-paper-section
          .paper-section-bank-login.row
            - if @representative.awaiting_acceptance?
              = render "family_dashboards/account/pending"
            - elsif @representative.accepted?
              = render "family_dashboards/account/accepted"
            - elsif @representative.rejected?
              = render "family_dashboards/account/rejected"

app/views/family_dashboards/home.html.haml
= render "family_dashboards/home/banner"
= render "family_dashboards/home/what_we_do"
= render "family_dashboards/home/how_you_can_help"
= render "family_dashboards/home/how_does_this_work"
/ = render "family_dashboards/home/benefits"
= render "family_dashboards/home/faq"

app/views/family_dashboards/iso_home.html.haml
= render "dialer_dashboards/iso_home/banner"
= render "dialer_dashboards/iso_home/what_we_do"
= render "dialer_dashboards/iso_home/how_you_can_help"
= render "dialer_dashboards/iso_home/how_does_this_work"
/= render "dialer_dashboards/iso_home/benefits"
= render "dialer_dashboards/iso_home/faq"

app/views/family_dashboards/questionnaire.html.haml
.web_body
  .paper-section.dialer-section-questionnaire
    .paper-section-header
      %span Additional Information
    .paper-section-main.clearfix   
      .paper-section-main-sheet.first-paper-section.clearfix
        .paper-section-main-sheet.last-paper-section
          .paper-section-bank-login.row
            .paper-section-regular
              .paper-section-regular-header
                /%span To get to know you better.
                %span Additional Information
              .paper-section-regular-body
                .paper-section-regular-body-info
                  %span Please provide us with you mobile number.
                .paper-section-regular-body-info
                  = simple_form_for @questionnaire, url: questionnaire_action_family_dashboards_path do |f|
                    - if @questionnaire.errors.any? || @rep_dialer.errors.any?
                      %div{class: "alert alert-danger validation-errors"}
                        %ol{style: "list-style: decimal; padding-left: 20px"}
                          - @rep_dialer.errors.full_messages.each do |msg|
                            %li{style: "font-size: 15px; line-height: 1.5"}= msg
                          - @questionnaire.errors.full_messages.each do |msg|
                            %li{style: "font-size: 16px; line-height: 1.5"}= msg
                    /- (0...@questionnaire.questions.size).each do |i|
                    /  .form-label.dialer-setup-form-label
                    /    %span #{i+1}. #{@questionnaire.questions[i].question_text}
                    /  .form-input.dialer-setup-form-input
                    /    = f.input "answer#{i+1}",  as: :text, input_html: {class: 'textbox'}, label: false, error: false
                    = fields_for @rep_dialer do |rep_dialer_fields|
                      .form-label.dialer-setup-form-label
                        %span Mobile Number
                      .form-input.dialer-setup-form-input
                        = rep_dialer_fields.text_field :mobile_number, placeholder: 'Mobile Number', class: 'textbox form-control required email', label: false

                    .form-action.dialer-setup-form-action
                      = f.submit "Continue", class: "form-button flat-button button-submit"

app/views/family_dashboards/setup.html.haml
.web_body
  .paper-section
    .paper-section-header
      %span Setup
    .paper-section-main.clearfix   
      .paper-section-main-sheet.first-paper-section.clearfix
        .paper-section-main-sheet.last-paper-section
          .paper-section-bank-login.row
            .paper-section-regular
              .paper-section-regular-header
                %span Please include your Paypal account email. 
              .paper-section-regular-body
                .paper-section-regular-body-info
                  %span To guarantee the quickest disbursement of your payment once your produce a lead, please include below your Paypal email. If you do not have a Paypal add a valid email you wish to associate with a future Paypal account.
                .paper-section-regular-body-info
                  = simple_form_for @representative, url: setup_action_dialer_dashboards_path do |f|
                    .form-label.dialer-setup-form-label
                      %span Paypal Email
                    .form-input.dialer-setup-form-input
                      = f.input :paypal_email, input_html: {class: 'textbox'}, label: false, error: false
                    .form-action.dialer-setup-form-action
                      = f.submit "Continue", class: "form-button flat-button button-submit"