config/routes.rb
Buynance::Application.routes.draw do

  devise_for :rep_dialers, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope(:path_names => { :new => "merchant-cash-advance" }) do
    resources :profitabilities, :path => "calculator", :only => [:new, :create]
  end

  resources :static_pages, :except => [:new, :create, :show, :update, :destroy, :index, :edit] do
    collection do
      get 'about'
      get 'offer'
      get 'tos'
      get 'confirm_email'
      get 'error'
      get 'compare'
    end
  end
  
  resources :funder_dashboards, only: [:main, :make_offer, :pending_bids, :accepted_bids, :lost_bids, :won_bids], path: "funder_dashboard" do
    collection do
      get 'main'
      post 'make_offer'
      get 'pending_bids'
      get 'accepted_bids'
      get 'lost_bids'
      get 'won_bids'
    end
  end

  resources :businesses, :only => [:new, :create, :show], :path => "clients" do
    resources :offers, :only => [:index] do
      patch :accept
    end
    resources :bank_accounts
    member do
      patch :activate
    end
    collection do
      get 'show_offers'
      get 'confirm_account'
      post 'confirm_mobile'
      get 'disqualified'
      get 'qualified_market'
      get 'accept_offer'
    end
  end

  
  mount API::Base => '/api'
  mount Soulmate::Server, :at => "/sm"
  scope(:path_names => { :past_merchants => "funders", :financial_information => "financial" }) do
    resources :business_steps, :path => "register"
  end

  resources :funders
  resources :funding_steps, :path => "funding"
  resources :funder_sessions, :path => "funder_session", :only => [:new, :create, :destoy]
  resources :business_user_sessions, :path => "session", :only => [:new, :create, :destoy]
  
  resources :business_dashboards, :only => [:display_offers, :offer_accepted, :offer_funded, :reenter_market, :accept_offer] do
    collection do
      get "display_offers"
      get "offer_accepted", as: :offer_accepted
      get "offer_funded", as: :offer_funded
      get "reenter_market", as: :reenter_market
      post "accept_offer", as: :accept_offer
    end
  end

  resources :dialer_dashboards, only: [:home, :setup, :setup_action, :account], path: "friends" do
    collection do
      get 'home', as: :dialer_home
      get 'account', as: :dialer_account
      patch 'setup_action', as: :setup_action
      get 'setup', as: :setup
      get 'questionnaire', as: :questionnaire
      patch 'questionnaire_action', as: :questionnaire_action
    end
  end

  resources :family_dashboards, only: [:home, :setup, :setup_action, :account, :sign_in], path: "family" do
    collection do
      get 'home', as: :dialer_home
      get 'account', as: :dialer_account
      patch 'setup_action', as: :setup_action
      get 'setup', as: :setup
      get 'questionnaire', as: :questionnaire
      patch 'questionnaire_action', as: :questionnaire_action
      get 'sign_in', as: :sign_in
    end
  end

  get 'friends' => 'dialer_dashboards#home'
  get 'family' => 'family_dashboards#home'

  get 'offers' => 'business_dashboards#display_offers', as: :display_offers

  

  get 'login' => "business_user_sessions#new",      :as => :login
  get 'logout' => "business_user_sessions#destroy", :as => :logout
  get 'funder_login' => "funder_sessions#new",      :as => :funder_login
  get 'funder_logout' => "funder_sessions#destroy", :as => :funder_logout

  get '/signup' => 'businesses#new', :as => :signup
  get '/account' => 'businesses#show', :as => :account

  get 'tos'                   => 'static_pages#tos'
  get 'privacy'               => 'static_pages#privacy'
  get 'business-funding-calculator' => 'profitabilities#new'
  get 'blog'                  => 'static_pages#blog'
  get 'about'                 => 'static_pages#about'
  get 'products'                 => 'static_pages#compare'

  match 'activate/:activation_code' => "businesses#activate", via: :get
  post 'confirm_mobile' => 'businesses#confirm_mobile'

  get 'details' => 'businesses#details'
  get 'clients/twiml/:id' => 'businesses#twiml'
  
  get 'DLPHP/verification.php' => "bank_accounts#new"
  get '/bank_accounts/success' => "bank_accounts#success"
  get '/bank_accounts/failure' => "bank_accounts#failure", as: :bank_failure

  get '/offers/:offer_id/accept' => 'offers#accept'
  put '/offers/:offer_id/update' => 'offers#update'

  post 'user/recover_account'    => 'business_users#recover_account'
  post 'user/reset_password'     => "business_users#reset_password"
  get 'recover'                  => 'business_users#recover', :as => :recovery_path
  get 'activation'               => 'business_users#recovery_instructions', :as => :recovery_instructions_path
  get 'recover/:recovery_code' => "business_users#password", as: :recovery_password

  get 'dummy' => "static_pages#dummy"
  
  post 'call/:id' => 'routing_numbers#call'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  

  match '/', to: 'static_pages#dev', constraints: { subdomain: 'dev' }, via: [:get, :post, :put, :patch, :delete]
  match '/invite', to: 'contest#invite', constraints: { subdomain: 'dev' }, via: [:get, :post, :put, :patch, :delete]

  root 'static_pages#index'

  

end

app/controllers/family_dashboards_controller.rb
 class FamilyDashboardsController < ApplicationController

	layout "family_layout"

	before_filter :require_rep_dialer_family, except: [:home, :iso_home, :sign_in]

	force_ssl if: :not_linkedin?

	def home
		 pluggable_js(is_production: is_production)

	end

	def iso_home

	end

	def account

		@representative = current_rep_dialer_family
		pluggable_js(is_production: is_production, email: @representative.email, is_pending: @representative.awaiting_acceptance?, is_accepted: @representative.accepted?, is_rejected: @representative.rejected?)
		if @representative.awaiting_questionnaire?
			redirect_to action: :questionnaire
		end
	end

	def setup
		@representative = current_rep_dialer_family
	end

	def setup_action
		@representative = current_rep_dialer_family
		if @representative.update_attributes(representative_params)
			@representative.add_paypal
			redirect_to action: :account
		else
			render action: :setup
		end
	end

	def questionnaire
		@rep_dialer = current_rep_dialer_family
		pluggable_js(is_production: is_production, email: @rep_dialer.email)
		@questionnaire = Questionnaire.find_by(name: "family_questionnaire")
	end

	def questionnaire_action
		@rep_dialer = current_rep_dialer_family
		@questionnaire = Questionnaire.find_by(name: "rep_questionnaire")
		@rep_dialer.assign_attributes(representative_params)
		@rep_dialer.current_step = "questionnaire"
		#@questionnaire.assign_attributes(questionnaire_params)
		if ((@questionnaire.valid? and @rep_dialer.valid?) and @rep_dialer.role == "Friend") or (@rep_dialer.valid? and @rep_dialer.role == "Family")
			@questionnaire.save
			@rep_dialer.save
			(0...@questionnaire.questions.size).each do |i|
				question = @questionnaire.questions[i]
				Answer.create(answer_text: @questionnaire.send("answer#{i+1}".to_sym),
					question_id:  @questionnaire.questions[i].id, 
					rep_dialer_id: @rep_dialer.id)
			end
			QuestionnaireCompleted.create(questionnaire_id: @questionnaire.id, rep_dialer_id: @rep_dialer.id)
			@rep_dialer.complete_questionnaire
			redirect_to action: :account
		else
			render action: :questionnaire
		end
	end

	def sign_in
		session[:family_signup] = "true"
		session[:dialer_resource] = "Family"
		redirect_to rep_dialer_omniauth_authorize_path(provider: "linkedin", type: "Family"), method: :post
	end

	private

	def representative_params
      return params.require(:rep_dialer).permit(:mobile_number, :agree_confirmation) 
    end

    def questionnaire_params
    	return params.require(:questionnaire).permit(:answer1, :answer2, :answer3, :answer4, :answer5)
    end

    def not_linkedin?
    	((params[:linkedin] != "true") and !Rails.env.development?)
    end

end

app/views/family_dashboards/iso_home/_banner.html.haml
.dialer-banner-family.container-fluid
  .dialer-banner-linkedin
    - unless rep_dialer_signed_in?
      = link_to rep_dialer_omniauth_authorize_path(provider: "linkedin"), method: :post do
        = image_tag("dialer_linkedin_signin.png", style: "width:26.8em;height:6.5em;")

app/views/family_dashboards/iso_home/_benefits.html.haml
#dialer_benefits.dialer-fluid
  .dialer-section.dialer-benefits
    .dialer-section-header.highlight-green
      %span Benefits
    .dialer-section-sequence
      %table.tg{:style => "undefined;table-layout: fixed; width: 90.0em"}
        %colgroup
          %col{:style => "width: 30.0em"}/
          %col{:style => "width: 7.5em"}/
          %col{:style => "width: 19.0em"}/
          %col{:style => "width:  4.5em"}/
          %col{:style => "width: 29.0em"}/
        %tr.dialer-section-sequence-images
          %th.tg-wm6t
            = image_tag("green_one.jpg")
          %th.tg-rd2y
          %th.tg-031e
            = image_tag("green_two.jpg")
          %th.tg-031e
          %th.tg-031e
            = image_tag("green_three.jpg")
        %tr.dialer-section-sequence-images
          %td.squence-images-main
            = image_tag("dialer_benefit_image_1.jpg", style: "width: 26.5em; height: 12.8em;")
          %td.tg-rd2y
            = image_tag("green_arrow.jpg", style: "width: 1.1em; height: 1.8em;")
          %td.squence-images-main
            = image_tag("dialer_benefit_image_2.jpg", style: "width: 18.1em; height: 6.4em;")
          %td.tg-031e
            = image_tag("green_arrow.jpg", style: "width: 1.1em; height: 1.8em;")
          %td.squence-images-main
            = image_tag("dialer_benefit_image_3.jpg", style: "width: 14.1em; height: 9.8em;")
        %tr.dialer-section-sequence-text.highlight-green
          %td.tg-wm6t
            %span Win hourly, daily, weekly, and monthly bonuses.  
          %td.tg-rd2y
          %td.tg-031e
            %span Set your own hours, be your own boss.
          %td.tg-031e
          %td.tg-031e
            %span Access to our Friends only forum for tips and tricks on how to get better.
    - unless rep_dialer_signed_in?
      .dialer-benefit-linkedin
        = link_to rep_dialer_omniauth_authorize_path(provider: "linkedin"), method: :post do
          = image_tag("dialer_linkedin_signin.png", style: "width:26.8em;height:6.5em;")

app/views/family_dashboards/iso_home/_faq.html.haml
#dialer_faq.dialer-fluid-gray
  .dialer-section
    .dialer-section-header
      %span FAQ
    .dialer-section-faq
      .dialer-section-faq-item
        .dialer-section-faq-item-header.clearfix
          .dialer-section-faq-item-header-number
            = image_tag("gray_one.png")
          .dialer-section-faq-item-header-text
            %span Do I have to keep set hours?
        .dialer-section-faq-item-text
          %span The goal we set for you is to earn for yourself; $100k in 9 months.  To achieve that goal you will have to work your rear off for it. 
      .dialer-section-faq-item
        .dialer-section-faq-item-header.clearfix
          .dialer-section-faq-item-header-number
            = image_tag("gray_two.png")
          .dialer-section-faq-item-header-text
            %span Is there training?
        .dialer-section-faq-item-text
          %span Absolutely.  Not only will you be trained on how to get deals done, but how to market for yourself so that after the 9th month, you leave with a book of business and most importantly, confidence.  
      .dialer-section-faq-item
        .dialer-section-faq-item-header.clearfix
          .dialer-section-faq-item-header-number
            = image_tag("gray_three.png")
          .dialer-section-faq-item-header-text
            %span How do I get leads?
        .dialer-section-faq-item-text
          %span You will get access to our dialers.  That’s not all.  We will train you on a system that is designed to after 6 months, get you on the groove path to getting your own inbound leads.  Our organic inbound leads will be distributed on a performance basis.  The more you make… the more you make.  
      .dialer-section-faq-item
        .dialer-section-faq-item-header.clearfix
          .dialer-section-faq-item-header-number
            = image_tag("gray_four.png")
          .dialer-section-faq-item-header-text
            %span Can I have people under me?
        .dialer-section-faq-item-text
          %span Certainly.  However, it will be at your own expense.  We have some methods we will show you as to how you can use personal virtual assistant labor for less than $150 per week to achieve a fantastic ROI.
      .dialer-section-faq-item
        .dialer-section-faq-item-header.clearfix
          .dialer-section-faq-item-header-number
            = image_tag("gray_five.png")
          .dialer-section-faq-item-header-text
            %span When can I start?
        .dialer-section-faq-item-text
          %span After individual interviews and group training, you should be ready to fly!

app/views/family_dashboards/iso_home/_how_does_this_work.html.haml
#dialer_work.dialer-fluid
  .dialer-section
    .dialer-section-header.highlight-blue
      %span How Does This Work?
    .dialer-section-text{style: "margin-bottom: 20px;"}
      %span Hi, I’m Jay Ballentine – Head of the Family.  I am super excited by what we have built. 
    .dialer-section-text{style: "margin-bottom: 20px;"} 
      %span I started off as a cold call lead generator in the business cash advance industry and ultimately grew into a broker, marketing thought leader, author, and ultimately marketing consultant.  Buynance, for all intents and purposes has been a work in progress for the better part of 4 years.  Life is full of fits and starts. One thing remains constant; winners always dust themselves up and get back up.  We set ambitious goals for the Buynance Family, achievable goals.  So, when you’re accepted in, it is because we will have felt like you have what it takes to win.  I want to take a moment to emphasize teamwork because that’s what this is about.  We are here to help, support, and push each other to be nothing but great.  Great teams start with great people.  For those of you who will be accepted into the Family, let me congratulate you in advance and leave you with this…
    .dialer-section-text 
      %span Hard work pays off.  Dreams do come true.  Bad times don’t last…  But good guys do.

app/views/family_dashboards/iso_home/_how_you_can_help.html.haml
#dialer_help.dialer-fluid-gray
  .dialer-section
    .dialer-section-header.highlight-green
      %span The Buynance Difference
    .dialer-section-text{style: "margin-bottom: 40px;"}
      %span{style: "font-family: latobold; margin-right: 10px; color: #20acd7;"} RESPECT: 
      %span Most alternative business funding companies rely on their brorker partners to produce business.  However, they have little respect or regard for them.  This is where they are weak.  This is where Buynance is strong.  Most firms want you to come on board produce business and kick you to the curb with absolutely nothing when it’s time for you to leave.  You will have worked hard, built a book, only to have nothing when you decide to fly on your own.  We’re turning that model on its head.  While you will always be considered family, our goal is to push you from the nest in 9 months.  Every Family member is expected to earn themselves no less than $100k in their first 9 months.  Those who reach this goal, will leave with the book of business that generated that $100k without fear of being sued. 
      %br
    .dialer-section-text{style: "margin-bottom: 40px;"}
      %span{style: "font-family: latobold; margin-right: 10px; color: #20acd7;"} EXPEDIENCY: 
      %span Most firms are heavily paper driven.  In order to get an approval and to get a deal done, you have to fight with the business owner for pieces of paper.  Not with Buynance.  Generally speaking, when you get a deal done you have to wait a week or more to be paid.  Not with Buynance.  Buynance pays same day commissions.
      %br 
    .dialer-section-text
      %span{style: "font-family: latobold; margin-right: 10px; color: #20acd7;"} MARKETING: 
      %span Some of you will start off on our dialers.  That’s only the start.  Jay Ballentine – Head of the Family, marketing consultant and author of “Mastermind: Merchant Cash Advance Marketing Vol. 1.” stands ready to invest his time, energy, and genius into helping all members of the Family generate consistent pipelines of inbound leads.  We are data driven marketing fanatics and firmly believe you should do all you can to meet customers where they are likely to be.  Nonetheless, you will learn things that will sustain your small business funding practice, long after Buynance.  
      %br

app/views/family_dashboards/iso_home/_what_we_do.html.haml
#dialer_why.dialer-fluid
  .dialer-section
    .dialer-section-header.highlight-blue
      %span What We Do
    .dialer-section-text
      %span We pair the power of technology behind who we are as people to help small business owners obtain super fast alternate small business funding. Business owners who demonstrate a need agree to sell us a portion of their future sales to pay for the things they need now. 
      = link_to  "/about",  :target => "_blank" do
        %span.highlight-blue{style:"text-decoration: underline"} You can read more about our story here
      %span . 